/**
 * This file is GENERATED by `npm run generate:api` from ../API_CONTRACT.yaml.
 *
 * The committed copy below is a minimal hand-stub so the project type-checks
 * before the first generation runs. CI runs `generate:api` and then
 * `git diff --exit-code` to catch drift.
 *
 * Once you `npm install`, run `npm run generate:api` to replace this file.
 */

// ─── Hand-stub: the absolute minimum to keep the openapi-fetch client typed.
// `openapi-typescript` will overwrite this with the full surface.

export interface paths {
  [path: string]: unknown;
}

export interface components {
  schemas: {
    // Minimal envelope/error shapes mirrored from CONVENTIONS.md.
    Error: {
      error: {
        code: string;
        message: string;
        i18nKey?: string;
        details?: Record<string, unknown>;
      };
    };
    Pagination: {
      nextCursor?: string | null;
      hasMore?: boolean;
      page?: number;
      pageSize?: number;
      total?: number;
      totalPages?: number;
    };
    User: {
      id: string;
      email: string;
      name?: string;
      role: "admin" | "maintainer" | "member" | "external";
      isActive: boolean;
      locale?: "en" | "id";
      groups?: string[];
      createdAt: string;
      updatedAt?: string;
    };
    AssetModelSummary: {
      id: string;
      name: string;
      categorySlug?: string;
      categoryName?: string;
      tags?: string[];
      status?: string;
      condition?: string;
      coverPhotoUrl?: string;
      unitCount?: number;
      availableCount?: number;
    };
    AssetModelDetail: {
      id: string;
      name: string;
      description?: string;
      category?: { id: string; slug: string; name: string };
      tags?: string[];
      customFields?: Array<{ key: string; label: string; type: string; value?: unknown }>;
      photos?: Array<{ id: string; url: string }>;
      companions?: Array<{ id: string; name: string; coverPhotoUrl?: string; publicHref?: string }>;
      usageSopHtml?: string;
      units?: AssetUnit[];
      createdAt?: string;
      updatedAt?: string;
    };
    AssetUnit: {
      id: string;
      modelId: string;
      serialNumber?: string;
      assetTag?: string;
      publicId: string;
      status: string;
      condition: string;
      location?: { room?: string; shelf?: string; cabinet?: string };
      purchase?: {
        price?: number;
        date?: string;
        usefulLifeMonths?: number;
        salvageValue?: number;
        depreciationMethod?: "straight_line" | "declining_balance" | "none";
      };
      currentHolder?: { id: string; name: string } | null;
      photos?: Array<{ id: string; url: string }>;
      internalNotes?: string;
    };
    Notification: {
      id: string;
      titleI18nKey: string;
      params?: Record<string, string | number>;
      link?: string;
      readAt?: string | null;
      createdAt: string;
    };
    PublicAssetView: {
      publicId: string;
      modelName: string;
      modelDescription?: string;
      categoryName?: string;
      tags?: string[];
      coverPhotoUrl?: string;
      gallery?: Array<{ id: string; url: string }>;
      unitStatus: "available" | "in_use" | "unavailable";
      usageSopHtml?: string;
      companions?: Array<{ name: string; coverPhotoUrl?: string; publicHref?: string }>;
    };
  };
  parameters: Record<string, never>;
  requestBodies: Record<string, never>;
  responses: Record<string, never>;
  headers: Record<string, never>;
  pathItems: Record<string, never>;
}

type AssetUnit = components["schemas"]["AssetUnit"];

export type operations = Record<string, unknown>;

export type webhooks = Record<string, never>;

export type $defs = Record<string, never>;
